DATASET:
  NAME: mscoco
  TRAIN:
    EXAMPLES: 149544
    PATTERN: tfrecords/train/*.tfrecord
  VAL:
    EXAMPLES: 6340
    PATTERN: tfrecords/val/*.tfrecord
  COMMON:
    IMAGE_NORM: true
    INPUT_SHAPE:
    - 192
    - 128
    - 3
    K: 17
    MEANS:
    - 0.485
    - 0.456
    - 0.406
    SIGMA: 2.0
    STDS:
    - 0.229
    - 0.224
    - 0.225

AUG:
  ALBUM: false
  FLIP_PROB: 0.5
  HALF_BODY_MIN_KP: 8
  HALF_BODY_PROB: 0.3
  KP_FLIP:
  - 0
  - 2
  - 1
  - 4
  - 3
  - 6
  - 5
  - 8
  - 7
  - 10
  - 9
  - 12
  - 11
  - 14
  - 13
  - 16
  - 15
  KP_UPPER:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  ROT_FACTOR: 45
  ROT_PROB: 0.6
  SCALE_FACTOR: 0.25

EVAL:
  BATCH_SIZE: 32
  COCO_JSON: datasets/mscoco/annotations/person_keypoints_val2017.json
  DO_EVAL: true
  EVAL_TERM: 5
  FLIP_TEST: true

MODEL:
  BACKBONE: ghostnetv2
  NAME: rle_model

TRAIN:
  BATCH_SIZE: 32
  EPOCHS: 270
  LR: 0.001
  LR_EPOCHS:
  - 170
  - 200
  LR_FACTOR: 0.1
  PRETRAINED: false

WANDB:
  NAME: null
  PROJECT: rle-pose
  SUBTITLE: small_input
  USE: true

OUTPUT:
  CKPT: null
  DIR: null